import { Suspense, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { getType } from '../file-types'
import type { FileData } from '../data.ts'
import { useFileBlob } from '../queries/useFileBlob.ts'
import { isHttpUrl } from '../bench/link/previewUrl.ts'
import { fetchFileBlob } from '../api.ts'
import { useActiveProject } from '../store.ts'

interface FileCardProps {
  file: FileData
  selected?: boolean
  onClick?: () => void
  onDelete?: () => void
}

/** Optimistic-upload ids generated by `src/app/data.ts:fileId()` look like
 *  `f<digits>-<timestamp>`. These aren't server ids, so `useFileBlob` must
 *  skip fetching them — server files have UUID-shaped ids. */
function isServerFileId(id: string): boolean {
  if (!id) return false
  if (/^f\d+-\d+$/.test(id)) return false
  return true
}

/** True if the string is a remote http(s) URL — used to distinguish link
 *  files (which carry a remote URL in `thumb`/`src`) from local blob URLs.
 *  Reuses the URL-parser-based check from `bench/link/previewUrl.ts`,
 *  which correctly rejects `data:`, `blob:`, protocol-relative, and
 *  malformed inputs. */
function isRemote(s: string | undefined): boolean {
  return !!s && isHttpUrl(s)
}

export default function FileCard({ file, selected, onClick, onDelete }: FileCardProps) {
  const { t } = useTranslation('files')
  const ft = getType(file.type)
  const canDelete = !!onDelete
  // Downloadable = any committed, server-backed file we own the bytes
  // for. Link files are just references (the backend would 302 to an
  // external URL), so they're excluded — the user can open the link
  // directly if they want the remote resource.
  const canDownload = file.type !== 'link' && isServerFileId(file.id)
  const [downloading, setDownloading] = useState(false)
  const handleDownload = async (e: React.MouseEvent) => {
    e.stopPropagation()
    if (downloading) return
    setDownloading(true)
    try {
      const blob = await fetchFileBlob(file.id)
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = file.name
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('[FileCard] download failed', err)
    } finally {
      setDownloading(false)
    }
  }

  // Stable blob URL from React Query. Keyed by the server file id, so the
  // `<img src>` attribute does not mutate across store-driven file list
  // refetches — fixing the CardGrid preview flicker. Disabled for:
  //  - optimistic local uploads (id matches the fileId() pattern),
  //  - file types that don't need a blob (links, fallback),
  //  - link files carrying a remote http(s) URL in thumb/src.
  //
  // The remote-URL check catches a corner case: `apiFileToFileData` may
  // leave a link file's `type` as e.g. `image` when the link points at an
  // image, which would otherwise flip `needsBlob` true and route the
  // backend through `/files/:id/download` for a link that isn't a blob.
  const needsBlob = ft.needsThumb || ft.needsSrc
  const isRemoteUrl = isRemote(file.thumb) || isRemote(file.src)
  const blobEnabled = needsBlob && !isRemoteUrl && isServerFileId(file.id)
  const { data: blobUrl } = useFileBlob(file.id, { enabled: blobEnabled })

  // Pull the project's file-server origin from the store and forward it
  // so the HTML Thumbnail can render its iframe. Other thumbnail types
  // ignore the field. Reading the store here (rather than in html.tsx)
  // keeps `file-types/*` free of store imports — that cycle was what
  // made `HtmlType` hit TDZ at module load.
  const fileServerRoot = useActiveProject()?.fileServerRoot ?? null

  // When the query has resolved, prefer its stable URL over the
  // store-written `thumb`/`src`. Otherwise fall through to whatever the
  // store has (optimistic preview, link URL, or in-flight `undefined`).
  const thumbFile = useMemo(() => {
    const base = blobUrl
      ? (ft.needsThumb ? { ...file, thumb: blobUrl } : { ...file, src: blobUrl })
      : file
    return { ...base, fileServerRoot }
  }, [file, blobUrl, ft.needsThumb, fileServerRoot])

  return (
    <div
      className={`app-card${selected ? ' bench-selected' : ''}`}
      data-filename={file.name}
      data-filetype={file.type}
      data-fileid={file.id}
      onClick={onClick}
    >
      <div className="app-card-thumb">
        <Suspense fallback={<span className="app-card-thumb-icon" dangerouslySetInnerHTML={{ __html: ft.icon }} />}>
          <ft.Thumbnail file={thumbFile} />
        </Suspense>
        {canDownload && (
          <button
            type="button"
            className={`app-card-download${canDelete ? ' app-card-download--with-delete' : ''}`}
            aria-label={t('card.downloadFile', { name: file.name })}
            title={t('card.download')}
            disabled={downloading}
            onClick={handleDownload}
          >
            {downloading ? (
              <span className="app-card-download-spinner" aria-hidden="true" />
            ) : (
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
            )}
          </button>
        )}
        {canDelete && (
          <button
            type="button"
            className="app-card-delete"
            aria-label={t('card.deleteFile', { name: file.name })}
            title={t('card.delete')}
            onClick={e => { e.stopPropagation(); onDelete!() }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="3 6 5 6 21 6" />
              <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
              <path d="M10 11v6" />
              <path d="M14 11v6" />
              <path d="M9 6V4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2" />
            </svg>
          </button>
        )}
      </div>
      <div className="app-card-info">
        <div className="app-card-name">{file.name}</div>
        <div className="app-card-meta">{ft.label} &middot; {file.size}</div>
      </div>
    </div>
  )
}
